# Generated by Django 4.1.1 on 2022-10-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
    ]
